version: 2

updates:
  - package-ecosystem: 'npm'
    schedule:
      interval: 'weekly'
      # Check for npm updates on Sundays
      day: 'sunday'
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: 'develop'
    # Labels on pull requests for security and version updates
    labels:
      - 'npm dependencies'
